# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f72f911f8c754026d1f36e56d90caff78ded5399a1e1d39b41577dd9b1e573de357cfb4863404f3888a76b04a606476a52afee744d58c1ed0026d2aecf3989aa

test:
  secret_key_base: c9b37b77ab756cf202b8359e1fa3a92942efeaf5c31893181fe0dbd421f948f01fe2f140047de972b0d16a23135e41d7d7db275afd95f2eb0845b71f216ae392

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
